# Generated by Django 4.2.5 on 2024-03-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0003_question_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название группы', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя студента', max_length=20)),
                ('surname', models.CharField(help_text='Фамилия студента', max_length=30)),
                ('father_name', models.CharField(help_text='Отчество студента', max_length=30)),
                ('number', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentforum.group')),
            ],
        ),
        migrations.RemoveField(
            model_name='parenttheme',
            name='child_theme',
        ),
        migrations.RemoveField(
            model_name='parenttheme',
            name='parent_theme',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='author',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='ParentTheme',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='req',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentforum.student'),
        ),
    ]
