# Generated by Django 4.2.5 on 2024-03-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0005_req_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название статуса', max_length=30)),
            ],
        ),
    ]
