# Generated by Django 4.2.5 on 2024-03-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0006_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='process',
        ),
        migrations.AddField(
            model_name='req',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='studentforum.status'),
        ),
    ]
