# Generated by Django 4.2.5 on 2024-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0007_remove_req_process_req_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='type',
            field=models.CharField(default='Справка о том, что является студентом', help_text='Тип справки', max_length=100),
        ),
    ]
