# Generated by Django 4.2.5 on 2024-10-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0008_req_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='study_form',
            field=models.CharField(choices=[('ochno', 'очная'), ('zaochno', 'заочная'), ('vecher', 'вечерняя')], default=('ochno', 'очная'), max_length=7),
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.IntegerField(default=1, help_text='Год обучения'),
        ),
        migrations.AddField(
            model_name='student',
            name='document',
            field=models.CharField(default='Приказ о зачислении №1111/у от 04.08.2014', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_form',
            field=models.CharField(choices=[('goverment', 'бюджетная'), ('personal', 'платная')], default=('goverment', 'бюджетная'), max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(help_text='Группа', on_delete=django.db.models.deletion.PROTECT, to='studentforum.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(help_text='Номер студенческого'),
        ),
    ]
