# Generated by Django 4.2.5 on 2024-10-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0010_group_cafedra'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='end_year',
            field=models.IntegerField(default=2021, help_text='Год окончания'),
        ),
    ]
